=== Katinuta/xmlparsing/data/vegetable.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/salad"
        xmlns:tns="http://www.example.com/salad"
        elementFormDefault="qualified">

    <element name="vegetable" abstract="true" type="tns:vegetable"/>
    <element name="fruit-vegetable" type="tns:fruit-vegetable" substitutionGroup="tns:vegetable"/>
    <element name="rootcrop" type="tns:rootcrop" substitutionGroup="tns:vegetable"/>
    <element name="leafy-vegetable" type="tns:leafy-vegetable" substitutionGroup="tns:vegetable"/>

    <element name="salad">
        <complexType>
            <sequence>
                <element ref="tns:vegetable" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>


    <complexType name="fruit-vegetable">
        <complexContent>
            <extension base="tns:vegetable">
                <sequence>
                    <element name="using-seeks" type="boolean" default="false"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="rootcrop">
        <complexContent>
            <extension base="tns:vegetable">
                <sequence>
                    <element name="deleting-cork" type="boolean" default="false"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="leafy-vegetable">
        <complexContent>
            <extension base="tns:vegetable">
                <sequence>
                    <element name="using-stalk" type="boolean" default="false"/>
                    <element name="using-leaf" type="boolean" default="false"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="vegetable">
        <sequence>

            <element name="caloricity">
                <simpleType>
                    <restriction base="positiveInteger">
                        <minInclusive value="10"/>
                        <maxInclusive value="150"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="weight">
                <simpleType>
                    <restriction base="positiveInteger">
                        <minInclusive value="1"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="composition" type="tns:composition"/>

            <element name="cutting-style" type="tns:cutting-style-type"/>

        </sequence>
        <attribute name="way-cooking" use="optional" default="raw" type="tns:way-cooking-type"/>
        <attribute name="vegetable-id" type="tns:id-vegetable" use="required"/>

        <attribute name="vegetable-name" use="required">
            <simpleType>
                <restriction base="string">
                    <pattern value="\w{3,30}"/>
                </restriction>
            </simpleType>
        </attribute>

    </complexType>
    <simpleType name="id-vegetable">
        <restriction base="ID">
            <pattern value="c[0-9]{1,10}"/>
        </restriction>
    </simpleType>

    <complexType name="composition">
        <sequence>

            <element name="protein">
                <simpleType>
                    <restriction base="decimal">
                        <minInclusive value="0.1"/>
                        <maxInclusive value="10"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="carbohydrate">
                <simpleType>
                    <restriction base="decimal">
                        <minInclusive value="0.1"/>
                        <maxInclusive value="70"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="fat">
                <simpleType>
                    <restriction base="decimal">
                        <minInclusive value="0"/>
                        <maxInclusive value="3"/>
                    </restriction>
                </simpleType>
            </element>

        </sequence>
    </complexType>
    <simpleType name="way-cooking-type">
        <restriction base="string">
            <enumeration value="raw"/>
            <enumeration value="fry"/>
            <enumeration value="boil"/>
            <enumeration value="stew"/>
            <enumeration value="steam"/>
        </restriction>
    </simpleType>

    <simpleType name="cutting-style-type">
        <restriction base="string">
            <enumeration value="finedice"/>
            <enumeration value="shreading"/>
            <enumeration value="matchsticks"/>
            <enumeration value="largedice"/>
            <enumeration value="slicing"/>
            <enumeration value="rollcutting"/>
        </restriction>
    </simpleType>
</schema>

=== Katinuta/xmlparsing/data/vegetables.xml
<?xml version="1.0" encoding="UTF-8" ?>

<salad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.com/salad"
       xsi:schemaLocation="http://www.example.com/salad vegetable.xsd">

    <fruit-vegetable vegetable-id="c1" vegetable-name="tomato" way-cooking="stew">
        <caloricity>30</caloricity>
        <weight>300</weight>
        <composition>
            <protein>0.2</protein>
            <carbohydrate>11.1</carbohydrate>
            <fat>0.0</fat>
        </composition>
        <cutting-style>matchsticks</cutting-style>
        <using-seeks>true</using-seeks>
    </fruit-vegetable>

    <leafy-vegetable vegetable-id="c2" vegetable-name="cabbage">
        <caloricity>16</caloricity>
        <weight>1000</weight>
        <composition>
            <protein>1.2</protein>
            <carbohydrate>2.2</carbohydrate>
            <fat>0.2</fat>
        </composition>
        <cutting-style>shreading</cutting-style>
        <using-stalk>true</using-stalk>
        <using-leaf>true</using-leaf>
    </leafy-vegetable>

    <fruit-vegetable vegetable-id="c3" vegetable-name="zucchini" way-cooking="fry">
        <caloricity>15</caloricity>
        <weight>300</weight>
        <composition>
            <protein>1.2</protein>
            <carbohydrate>3.2</carbohydrate>
            <fat>0.1</fat>
        </composition>
        <cutting-style>slicing</cutting-style>
        <using-seeks>false</using-seeks>
    </fruit-vegetable>

    <leafy-vegetable vegetable-id="c4" vegetable-name="spinach">
        <caloricity>16</caloricity>
        <weight>200</weight>
        <composition>
            <protein>2.6</protein>
            <carbohydrate>3.0</carbohydrate>
            <fat>0.4</fat>
        </composition>
        <cutting-style>shreading</cutting-style>
        <using-stalk>false</using-stalk>
        <using-leaf>true</using-leaf>
    </leafy-vegetable>

    <fruit-vegetable vegetable-name="eggplant" vegetable-id="c5" way-cooking="stew">
        <caloricity>24</caloricity>
        <weight>100</weight>
        <composition>
            <protein>1.2</protein>
            <carbohydrate>5.1</carbohydrate>
            <fat>0.1</fat>
        </composition>
        <cutting-style>largedice</cutting-style>
        <using-seeks>true</using-seeks>
    </fruit-vegetable>

    <leafy-vegetable vegetable-id="c6" vegetable-name="parsley" way-cooking="raw">
        <caloricity>49</caloricity>
        <weight>10</weight>
        <composition>
            <protein>3.7</protein>
            <carbohydrate>8.0</carbohydrate>
            <fat>0.4</fat>
        </composition>
        <cutting-style>shreading</cutting-style>
        <using-stalk>false</using-stalk>
        <using-leaf>true</using-leaf>
    </leafy-vegetable>

    <fruit-vegetable vegetable-id="c7" vegetable-name="cucumber">
        <caloricity>14</caloricity>
        <weight>300</weight>
        <composition>
            <protein>0.8</protein>
            <carbohydrate>2.6</carbohydrate>
            <fat>0.1</fat>
        </composition>
        <cutting-style>finedice</cutting-style>
        <using-seeks>false</using-seeks>
    </fruit-vegetable>

    <fruit-vegetable vegetable-id="c8" vegetable-name="pepper">
        <caloricity>27</caloricity>
        <weight>400</weight>
        <composition>
            <protein>1.3</protein>
            <carbohydrate>5.3</carbohydrate>
            <fat>0.0</fat>
        </composition>
        <cutting-style>matchsticks</cutting-style>
        <using-seeks>false</using-seeks>
    </fruit-vegetable>

    <leafy-vegetable vegetable-id="c9" vegetable-name="fennel" way-cooking="raw">
        <caloricity>32</caloricity>
        <weight>20</weight>
        <composition>
            <protein>2.5</protein>
            <carbohydrate>4.1</carbohydrate>
            <fat>0.5</fat>
        </composition>
        <cutting-style>shreading</cutting-style>
        <using-stalk>true</using-stalk>
        <using-leaf>true</using-leaf>
    </leafy-vegetable>

    <fruit-vegetable vegetable-id="c10" vegetable-name="pumpkin" way-cooking="steam">
        <caloricity>25</caloricity>
        <weight>60</weight>
        <composition>
            <protein>1.9</protein>
            <carbohydrate>4.2</carbohydrate>
            <fat>0.1</fat>
        </composition>
        <cutting-style>finedice</cutting-style>
        <using-seeks>false</using-seeks>
    </fruit-vegetable>

    <fruit-vegetable vegetable-id="c11" vegetable-name="corn" way-cooking="boil">
        <caloricity>110</caloricity>
        <weight>300</weight>
        <composition>
            <protein>3.7</protein>
            <carbohydrate>23.4</carbohydrate>
            <fat>1.5</fat>
        </composition>
        <cutting-style>largedice</cutting-style>
        <using-seeks>true</using-seeks>
    </fruit-vegetable>

    <leafy-vegetable vegetable-id="c12" vegetable-name="sorrel">
        <caloricity>19</caloricity>
        <weight>10</weight>
        <composition>
            <protein>1.5</protein>
            <carbohydrate>3.0</carbohydrate>
            <fat>0.0</fat>
        </composition>
        <cutting-style>shreading</cutting-style>
        <using-stalk>false</using-stalk>
        <using-leaf>true</using-leaf>
    </leafy-vegetable>

    <fruit-vegetable vegetable-id="c13" vegetable-name="peas" way-cooking="stew">
        <caloricity>73</caloricity>
        <weight>150</weight>
        <composition>
            <protein>5.0</protein>
            <carbohydrate>12.8</carbohydrate>
            <fat>0.2</fat>
        </composition>
        <cutting-style>largedice</cutting-style>
        <using-seeks>true</using-seeks>
    </fruit-vegetable>

    <leafy-vegetable vegetable-id="c14" vegetable-name="salad">
        <caloricity>17</caloricity>
        <weight>200</weight>
        <composition>
            <protein>0.5</protein>
            <carbohydrate>2.3</carbohydrate>
            <fat>0.2</fat>
        </composition>
        <cutting-style>shreading</cutting-style>
        <using-stalk>false</using-stalk>
        <using-leaf>true</using-leaf>
    </leafy-vegetable>

    <fruit-vegetable vegetable-id="c15" vegetable-name="tomato" way-cooking="steam">
        <caloricity>30</caloricity>
        <weight>100</weight>
        <composition>
            <protein>0.2</protein>
            <carbohydrate>11.1</carbohydrate>
            <fat>0.0</fat>
        </composition>
        <cutting-style>finedice</cutting-style>
        <using-seeks>true</using-seeks>
    </fruit-vegetable>

    <fruit-vegetable vegetable-name="eggplant" vegetable-id="c16" way-cooking="fry">
        <caloricity>24</caloricity>
        <weight>100</weight>
        <composition>
            <protein>1.2</protein>
            <carbohydrate>5.1</carbohydrate>
            <fat>0.1</fat>
        </composition>
        <cutting-style>finedice</cutting-style>
        <using-seeks>false</using-seeks>
    </fruit-vegetable>

</salad>
